from src.general.props.NNMetric import NNMetrics

DEF_CUTOFF = 5.
DEF_ATOM_BASIS_SIZE = 10
DEF_NUM_OF_INTERACTIONS = 1
DEF_RBF_BASIS_SIZE = 10
DEF_LEARNING_RATE = 1e-4

DEF_LOG_SAVE_INTERVAL = 1
DEF_DIRECTORY_BREAK = 1000

DEF_CHECKPOINT_NUMBER_SAVES = 1
DEF_LOGGING_INTERVAL = 1
DEF_NUMBER_EPOCHS = 2

DEF_DISPLAY_METRICS = [NNMetrics.LOSS, NNMetrics.MAE, NNMetrics.MSE, NNMetrics.R2, NNMetrics.NRMSE,
                       NNMetrics.EPOCH_TIME, NNMetrics.EPOCH_MEMORY, NNMetrics.EPOCH_GPU_MEMORY]
