METRIC_NAME_SEPARATOR = "_"
METRIC_TRAIN_DESCR = "train"
METRIC_VALIDATION_DESCR = "val"
NN_PERFORMANCE_KPI = "val_loss"

LEARNING_RATE_KEY = "lr"
EPOCH_TENSORBOARD_KEY = "epoch"
SCALAR_TENSORBOARD_KEY = "scalars"

LOG_VERSION_DIR_FORMATS = "{log_dir}/version_{version}"